
export const CLOSE_APPLICATION_WINDOW = "CLOSE_APPLICATION_WINDOW";
export type CLOSE_APPLICATION_WINDOW = typeof CLOSE_APPLICATION_WINDOW

// STARTUP RELATED


export const DATABASE_READY = "DATABASE_READY";
export type DATABASE_READY = typeof DATABASE_READY


export const APPLICATION_TITLE_CHANGE = "APPLIATION_TITLE_CHANGE";
export type APPLICATION_TITLE_CHANGE = typeof APPLICATION_TITLE_CHANGE


export const WINDOW_CONTROL_ACTION_MAXIMIZED = "WINDOW_CONTROL_ACTION_MAXIMIZED";
export type WINDOW_CONTROL_ACTION_MAXIMIZED = typeof WINDOW_CONTROL_ACTION_MAXIMIZED

export const WINDOW_CONTROL_ACTION_RESTORE = "WINDOW_CONTROL_ACTION_RESTORE";
export type WINDOW_CONTROL_ACTION_RESTORE = typeof WINDOW_CONTROL_ACTION_RESTORE


export const WINDOW_CONTROL_ACTION_FULLSCREEN = "WINDOW_CONTROL_ACTION_FULLSCREEN";
export type WINDOW_CONTROL_ACTION_FULLSCREEN = typeof WINDOW_CONTROL_ACTION_FULLSCREEN

export const WINDOW_CONTROL_ACTION_SHOWAPPBAR = "WINDOW_CONTROL_ACTION_SHOWAPPBAR";
export type WINDOW_CONTROL_ACTION_SHOWAPPBAR = typeof WINDOW_CONTROL_ACTION_SHOWAPPBAR


export const VEHICLES_UPDATE_LIST = "VEHICLES_UPDATE_LIST";
export type VEHICLES_UPDATE_LIST = typeof VEHICLES_UPDATE_LIST


export const USERS_UPDATE_LIST = "USERS_UPDATE_LIST";
export type USERS_UPDATE_LIST = typeof USERS_UPDATE_LIST


export const LOGIN = "LOGIN";
export type LOGIN = typeof LOGIN

export const REGISTER = "REGISTER";
export type REGISTER = typeof REGISTER


export const FACE_DETECT = "FACE_DETECT";
export type FACE_DETECT = typeof FACE_DETECT


export const FACE_DETECT_ADD = "FACE_DETECT_ADD";
export type FACE_DETECT_ADD = typeof FACE_DETECT_ADD

export const NOTIFICATION = 'NOTIFICATION';
export type NOTIFICATION = typeof NOTIFICATION;
